#!/bin/sh -e

export DESTDIR="$1"

cmake -B build -G Ninja -Wno-dev \
        -DCMAKE_BUILD_TYPE=MinSizeRel \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_WSI_XCB_SUPPORT=ON \
        -DBUILD_WSI_XLIB_SUPPORT=ON \
        -DBUILD_WSI_WAYLAND_SUPPORT=OFF \
        -DBUILD_TESTS=OFF \

cmake --build build
cmake --install build

