#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DALLOW_EXTERNAL_SPIRV_TOOLS=yes \

cmake --build build
cmake --install build
